# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

ENABLE_LINTERS:
  - PYTHON_PYLINT
  - PYTHON_BLACK

GITHUB_STATUS_REPORTER: true
